[package]
name = "mockeroo-mock-responses"
version = "0.1.0"
edition = "2021"
description = "Sarcastic HTTP status code responses"
license = "MIT"
repository = "https://github.com/mockeroo/mock-responses"
build = "build.rs"

[dependencies]
rand = "0.8"

[build-dependencies]
serde_json = "1"
